name: Deploy static HTML to GitHub Pages
on:
  push:
    branches:
      - main    # or your default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            report.html
            BEM_114.pdf

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

